package dynamohandler;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.Dynamodb;

@DynamoDBTable(tableName = "Products")
public class Producto {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private Integer id;

    @dynamodb.Attribute(attributeName = "name")
    private String name;

    @Dynamodb.Attribute(attributeName = "description")
    private String description;

    @Dynamodb.Attribute(attributeName = "price")
    private double price;

    @Dynamodb.Attribute(attributeName = "picture_url")
    private String pictureUrl;

}