AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CreateProductDynamo - Products CRUD API backed by DynamoDB

Globals:
  Function:
    Runtime: java17
    CodeUri: ./
    Architectures:
      - x86_64
    MemorySize: 512
    Timeout: 20
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        DYNAMODB_TABLE: !Ref ProductsTable

Resources:

  CreateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dynamohandler.CreateProductHandler::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Events:
        CreateProduct:
          Type: Api
          Properties:
            Path: /products
            Method: post

  GetProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dynamohandler.GetProductHandler::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetProduct:
          Type: Api
          Properties:
            Path: /products
            Method: get

  UpdateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dynamohandler.UpdateProductHandler::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Events:
        UpdateProduct:
          Type: Api
          Properties:
            Path: /products
            Method: put

  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ProductsCRUD
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  ProductsApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/products/"
